---
# Default values for stratio-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: "postgres"

prometheus:
  rules:
    groups:
      - name: postgres
        rules:
          - name: PostgresqlDown
            expr: "pg_up == 1"
            for: "100m"
            labels:
              severity: "low"
