{{- range $.Values.prometheus.rules.groups }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "stratio-rules.labels" $ | nindent 4 }}
  name: stratio-operations-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  groups:
  - name: elasticsearch
    rules:
{{- range .rules }}
    - alert: {{ .name }}
      annotations:
      {{- if .annotations -}}
        {{ toYaml .annotations | nindent 8 }}
      {{- end }}
      expr: |
        {{ .expr }}
      for: {{ .for }}
      labels:
      {{- if .labels -}}
        {{ toYaml .labels | nindent 8 }}
      {{- end -}}
{{ end }}
{{- end }}
